<a href="https://colab.research.google.com/github/tincorpai/Deep_Learning_Pytorch/blob/master/Pytorch_Fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch Fundamental

Resources Notebooks Available Here: https://www.learnpytorch.io/01_pytorch_workflow/

If you have any questions, use this: https://github.com/mrdbourke/pytorch-deep-learning/discussions

The Zero to Mastery Website: https://zerotomastery.io/courses/learn-tensorflow/

The Zero to Mastery Discussion Community: https://discord.com/channels/423464391791476747/@home

For Google Colab Command Short Cut, Visit this site: https://amitness.com/2020/06/google-colaboratory-tips/

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


# Introduction to tensors 

## Creating Tensors 

Pytorch tensors are created using 'torch.Tensor()' = https://pytorch.org/docs/stable/tensors.html

In [ ]:
# scalar 
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
#Attributes of scalar 
#it has no dimension 
scalar.ndim

0

In [ ]:
#tensor as python int
scalar.item()

7

In [ ]:
#vector 
vector = torch.tensor([12, 22])
vector

tensor([12, 22])

In [ ]:
#how many dimensions a vectir has 
vector.ndim

1

In [ ]:
#shape of the vector
vector.shape

torch.Size([2])

In [ ]:
#create a matrix
MATRIX = torch.tensor([[12, 22, 33], [12, 33, 45]])
MATRIX

tensor([[12, 22, 33],
        [12, 33, 45]])

In [ ]:
#number of dimension of matrix 
MATRIX.ndim


2

In [ ]:
#Let's gets matrix shape
MATRIX.shape

torch.Size([2, 3])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 3, 4],
                        [2, 3, 4, 5],
                        [44, 3, 4, 5]]])
TENSOR

tensor([[[ 1,  2,  3,  4],
         [ 2,  3,  4,  5],
         [44,  3,  4,  5]]])

In [ ]:
#Get the dimension of tensor 
TENSOR.ndim

3

In [ ]:
#Number of tensor its return
TENSOR.shape[2]

4

In [ ]:
MUSIC = torch.tensor([[[[12, 22, 33, 4],
                        [23, 22, 33, 44],
                        [23, 44, 55, 44]]]])
MUSIC

tensor([[[[12, 22, 33,  4],
          [23, 22, 33, 44],
          [23, 44, 55, 44]]]])

In [ ]:
#number of dimension of MUSIC
MUSIC.ndim

4

In [ ]:
MUSIC.shape

torch.Size([1, 1, 3, 4])

In [ ]:
VISION = torch.tensor([[[[12, 22, 33, 4],
                        [23, 22, 33, 44],
                        [23, 44, 55, 44]]],
                       [[[20, 22, 33, 4],
                        [23, 30, 33, 44],
                        [23, 44, 50, 44]]]])
VISION

tensor([[[[12, 22, 33,  4],
          [23, 22, 33, 44],
          [23, 44, 55, 44]]],


        [[[20, 22, 33,  4],
          [23, 30, 33, 44],
          [23, 44, 50, 44]]]])

In [ ]:
VISION.ndim

4

In [ ]:
VISION.shape

torch.Size([2, 1, 3, 4])

For Matrix and tensor, you have an upper case

## Random Tensors

Why random tensors?

Random tensors are important because the way many neural network works is that they starts with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -. update random numbers -> look at data -> update random numbers`

To learn more about torch.rand, go to https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
#create a random tensors with Pytorch of shae (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7576, 0.6748, 0.9498, 0.0239],
        [0.4532, 0.1975, 0.0019, 0.9408],
        [0.5241, 0.5041, 0.0855, 0.7181]])

In [ ]:
random_tensor.ndim, random_tensor.shape

(2, torch.Size([3, 4]))

In [ ]:
#create a random tensor to similar shape to an image tensor 
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width,colour channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and Ones


You create random tensors of all zeros when you want to mask out a tensor we can multiply the target tensor by zeros or you want to mask out a particular column in a tensor, you can create zero tensor for that particular column.

For adequate understanding of zeros and ones tensors, checkout the following links:

zero tensors: https://pytorch.org/docs/stable/generated/torch.zeros.html

Ones tensors: https://pytorch.org/docs/stable/generated/torch.ones.html

In [ ]:
# Create a tensors of all zeros 
#This is useful when creating a mask
zero = torch.zeros(size = (3, 4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zero*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

## Creating a range of tensors and tensors like 

For a doumentation on torch.arange, visit this link: https://pytorch.org/docs/stable/generated/torch.arange.html

In [ ]:
#use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#tensor like. This helps to create a tensor that looks like the original
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#use torch.range()
one_to_20 = torch.arange(start=1, end = 21, step = 1)
one_to_20

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])

In [ ]:
#tensor like. This helps to create a tensor that looks like the original
ten_zeros = torch.zeros_like(input=one_to_20)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

The datatype represents how much details a single number is stored in memory.

**Note:** Tensor datatype is one of the 3 big errors you will run into in Pytorch and in Deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device.

Precision in computing: https://en.wikipedia.org/wiki/Precision_(computer_science)#:~:text=In%20computer%20science%2C%20the%20precision%20of%20a%20numerical,digits%20that%20are%20used%20to%20express%20a%20value.

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #what datatpe is 
                               device=None, #What device is your device on 
                               requires_grad=False #whether or not to track the
                               )
                               

In [ ]:
float_32_tensor.dtype

torch.float32

## Mutiplying different datatypes

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int64)

In [ ]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

## Getting Information from tensors:

1. Tensors not right datatype - to get datatype from a tensor, use tensor.dtype
2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device. - to get device from a tensor, use tensor.device 

In [ ]:
#Create a tensor 
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4388, 0.2399, 0.8877, 0.3187],
        [0.5221, 0.4154, 0.1345, 0.8345],
        [0.1385, 0.4941, 0.4837, 0.0265]])

In [ ]:
#find out details about some tensor 
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.device}")

tensor([[0.4388, 0.2399, 0.8877, 0.3187],
        [0.5221, 0.4154, 0.1345, 0.8345],
        [0.1385, 0.4941, 0.4837, 0.0265]])
Datatype of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
Datatype of tensor: cpu


## Manipulating Tensors

Tensor operations include:

* Addition 
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

To find patterns in the dataset, a neural network will combine one or combination of these operations in any shapes or forms.

In [ ]:
#Create a tensor add 100 to it
tensor = torch.tensor([1, 2, 3, 4])
tensor + 100

tensor([101, 102, 103, 104])

In [ ]:
#multiply tensor by 10
tensor * 10

tensor([10, 20, 30, 40])

In [ ]:
#substract 10 from tensor 
tensor - 10

tensor([-9, -8, -7, -6])

In [ ]:
#try out pytorch in-built tensor 
torch.mul(tensor, 10)

tensor([10, 20, 30, 40])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13, 14])

## MAtrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning 

1. Element-wise multiplication 
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The inner dimension must match: 

* (3, 2) @ (3, 2) won't work
* (2, 3) @ (3, 4) works
* (3, 3) @ (3, 4) works

The resulting matrix has the shape of the **outer dimensions:**

* (2, 3) @ (3, 4) -> (2, 2)
* (3, 2) @ (2, 3) -> (3, 3)

In [ ]:
#Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3, 4]) * tensor([1, 2, 3, 4])
Equals: tensor([ 1,  4,  9, 16])


In [ ]:
# matrix store the result of multiplication in torch.matmul
torch.matmul(tensor, tensor)

tensor(30)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 321 µs, sys: 33 µs, total: 354 µs
Wall time: 362 µs


tensor(30)

## one of the most common error in deep learning: shape errors



In [ ]:
torch.matmul(torch.rand(10, 3), torch.rand(3, 10))

tensor([[0.5925, 0.4792, 0.2585, 0.8032, 0.7649, 0.2651, 0.1926, 0.4620, 0.2936,
         0.3047],
        [0.6770, 0.8038, 0.6305, 0.9414, 0.8570, 0.1360, 0.2847, 0.5649, 0.3695,
         0.7207],
        [0.6425, 0.5409, 0.1574, 0.7612, 0.6994, 0.2169, 0.2403, 0.4233, 0.2138,
         0.2348],
        [0.8304, 0.9328, 0.5938, 1.0681, 0.9606, 0.1600, 0.3549, 0.6262, 0.3677,
         0.7144],
        [0.7786, 0.7790, 0.6469, 1.1523, 1.0908, 0.2932, 0.2714, 0.6886, 0.4853,
         0.7114],
        [1.3445, 1.2258, 0.8907, 1.9265, 1.8315, 0.5576, 0.4506, 1.1341, 0.7721,
         0.9960],
        [1.2211, 0.9039, 0.3387, 1.5847, 1.5096, 0.5688, 0.3905, 0.8945, 0.5334,
         0.4353],
        [1.4035, 1.2843, 0.9234, 2.0023, 1.9009, 0.5743, 0.4738, 1.1778, 0.7977,
         1.0360],
        [0.3604, 0.5332, 0.8900, 0.8200, 0.8051, 0.1606, 0.1059, 0.5391, 0.5077,
         0.8865],
        [0.9270, 0.6979, 0.5306, 1.3958, 1.3659, 0.5215, 0.2546, 0.8192, 0.5906,
         0.5642]])

In [ ]:
# shapes for matrix multiplication
tensor_A =  torch.tensor([[1, 2],
                          [3, 4],
                          [5, 6]])

tensor_B = torch.tensor([[7, 16],
                         [8, 11],
                         [9, 12]])

In [ ]:
#perform a transpose on tensor B
torch.mm(tensor_A, tensor_B.T)

tensor([[ 39,  30,  33],
        [ 85,  68,  75],
        [131, 106, 117]])

To fix our tensor shape issues, we can manipilate the shape of one of our tensors using a transpose .

In [ ]:
#Matrix operation works when tensor B is transpose 
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
output:

tensor([[ 39,  30,  33],
        [ 85,  68,  75],
        [131, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc(tensor aggregation)

In [ ]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x)

tensor(90)

In [ ]:
# find the mean - notes the torch.mean() function requires a tensor of float32 datatype to work.

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()


(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the Positional Min and max


In [ ]:
#Find the position in tensor that has a minimum value with argmin-> returns index position of target where the minimum value occurs.
x.argmin()

tensor(0)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - stacking, squeezing and unsqueezing tensors
* View - Return a veiw of an input tensor of certain shape but keep the same memory
* Stacking - combine multiple tensors on top of each other (vstack) or side by side.

* Squeeze - remove all '1' dimension from a tensor

* Unsqueeze - add a '1' dimension to a target tensor.

* Permute - Return a view of the input with the dimensions permuted (swapped) in a certain way.

In [ ]:
# Let's create a tensor 
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor the same )
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stack tensors on top of each other 
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
## torch.squeeze() - remove all single dimensions from a target vector 
x = torch.zeros(2, 1, 2, 1, 2)
x.size()
torch.Size([2, 1, 2, 1, 2])
y = torch.squeeze(x)
y.size()
torch.Size([2, 2, 2])
y = torch.squeeze(x, 0)
y.size()
torch.Size([2, 1, 2, 1, 2])
y = torch.squeeze(x, 1)
y.size()
torch.Size([2, 2, 1, 2])

torch.Size([2, 2, 1, 2])

In [ ]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [ ]:
torch.Size([2, 1, 2, 1, 2])
y = torch.squeeze(x)

In [ ]:
y.size()

torch.Size([2, 2, 2])

In [ ]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

# This happans when there is a dimension mis-match 
# Remove extra dimensions from x_reshaped 



In [ ]:
#Squeeze out all single dimension of them 
# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


New tensor tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - add a single dimension to a target tensor at a specific dim 
print(f"previous target: {x_squeezed}")
print(f"previous shape: {x_squeezed.shape}")


# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
#you use permute with images
#they share the same space and memory as x_original
x_original = torch.rand(size = (224, 224, 3))  #[height, width, colour_channels]

# Permut the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) #shift axis 0->, 1->2, 2->0


print(f"Previous shape: {x_original.shape}")
print(f"New shape:{x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape:torch.Size([3, 224, 224])


In [ ]:
## select data from tensor with indexing
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0] #zero bracket


tensor([1, 2, 3])

In [ ]:
#let's index on the first row 
x[0][0]

tensor([1, 2, 3])

In [ ]:
#let's index on the most inner bracket (last dimension)
x[0][1][1]

tensor(5)

In [ ]:
#youcan also use a ":" to select "all" of the target dimension
x[:, :, ]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
#select all values of the 0th and the 1st dimension but only index 1 of the 2nd dimensions
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
#Get  index 0 of the 0th dimension and all the values of the 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
#index on x to return 9
x[0, 2, 2]

tensor(9)

In [ ]:
#index on x to return the last column
x[0, :, 2]

tensor([3, 6, 9])

## Pytorch tensors @ Numpy

Numpy is a popular scientific Python numerical computing library.

* Data in Numpy, want in Pytorch tensor -> torch.from_numpy(ndaray)
* Pytorch tensor -> Numpy -> tourch.Tensor.numpy()

In [ ]:
#numpy array to tensor 
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32) #convert from numpy to tensor 
#when converting python's from numpy array to tensor, tensor will retain the datatype of 
#the numpy unless orderwise indicated.
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float32)

## Reproducibility  (trying to take random out of random)
In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try
make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and Python comes the concept of a **random seed**


Essentially, what the random seed does is "flavour" the randomness.



In [ ]:
torch.rand(3, 3)

tensor([[0.2479, 0.2598, 0.9795],
        [0.6332, 0.4897, 0.0675],
        [0.9900, 0.9664, 0.8818]])

In [ ]:
#create two random tensors 
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

In [ ]:
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B) #None of the elements are equal.


tensor([[0.2153, 0.2984, 0.3880, 0.7171],
        [0.4298, 0.8730, 0.2406, 0.3612],
        [0.2747, 0.1984, 0.8739, 0.8835]])
tensor([[0.2768, 0.2486, 0.3461, 0.5279],
        [0.2906, 0.6228, 0.8684, 0.8621],
        [0.1339, 0.5243, 0.3137, 0.2000]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#Let's male some random but reproducible tensors 
#set the random seed 
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)


print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)  #its only work for one line of code.

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra Resources for Reproducibility

## Running tensors and Pytorch objects on GPUs (and making faster compuation)
GPU = faster computation on numbers, thanks to cuda + nvidia + Pytorch working behind the sceens

1) easiest -  Use Google colab for free GPU (options to upgrade as well)

2) Use your own GPU as well but this requires alot of investment of purchasing a GPU, there's lots of options...

3)Usse cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them.

For 2, 3 Pytorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started

In [ ]:
!nvidia-smi

Sun Feb  5 17:56:51 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   46C    P0    23W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU access with PyTorch

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code:

https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. run on GPU if available, else default to CPU.

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
# setup device agnostic code: This is important because you might not always have access to GPU, however, if there was access to GPU, use it when it is available.
device = "cuda" if torch.cuda.is_available() else "cpu" #This means check if cuda is available, if it is use it if not use "cpu"
device 

'cuda'

In [ ]:
# Count number of devices: count tne number of device available.
torch.cuda.device_count()

1

## Putting tensors (and models) on GPU


The reason we want our tensors/models on GPU is because using a GPU results in faster computation.

This is because it is much faster to run tensors operations on GPU.

In [ ]:
#Create a tensor (default on the CPU): by default, device parameter is on CPU
tensor = torch.tensor([1, 2, 3])

#Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available): This method will work on what ever target device available.
#it can also be use for models.
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensor back to the cpu


In [ ]:
# If tensor is on GPU, can't transform it to Numpy: We need to call tensor.cpu() to bring back to cpu then use numpy on it.
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Excercises

In [ ]:
# Create a random tensor with shape (7, 7)
a = torch.rand(7, 7)
a

tensor([[2.0943e-02, 7.3708e-02, 5.4186e-01, 3.1255e-01, 8.5121e-01, 9.1982e-01,
         4.8423e-01],
        [6.9769e-01, 2.1815e-01, 7.3756e-01, 3.1769e-01, 2.1356e-01, 2.2877e-01,
         3.9812e-01],
        [2.7546e-01, 2.8978e-01, 4.3005e-01, 8.0240e-01, 2.6956e-01, 7.8491e-01,
         6.7034e-01],
        [3.7774e-01, 3.0536e-01, 9.7119e-01, 1.0322e-01, 1.0952e-01, 9.4265e-01,
         1.8185e-01],
        [2.3081e-01, 1.9437e-01, 1.5463e-01, 4.2298e-01, 7.2333e-01, 3.0933e-01,
         3.3695e-01],
        [5.5237e-01, 7.3752e-01, 9.1673e-01, 6.3347e-01, 5.0799e-01, 5.7235e-01,
         9.7072e-04],
        [8.8905e-01, 4.5855e-02, 2.6795e-01, 3.6608e-01, 9.3206e-01, 1.6052e-01,
         7.3058e-01]])

In [ ]:
# Create a matrix multiplication on the tensor 2 with another random tensor (1, 7)
# because the inner index is the same, you can multiply the two matrix 
b = torch.rand(1, 7).T
b

tensor([[0.7658],
        [0.7389],
        [0.6624],
        [0.0110],
        [0.1300],
        [0.8630],
        [0.3789]])

In [ ]:
torch.matmul(a, b)

tensor([[1.5207],
        [1.5635],
        [1.6851],
        [2.0560],
        [0.9160],
        [2.1424],
        [1.4327]])